import Head from 'next/head'
import PrintButton from '../component/PrintButton/Index'
import styles from '../styles/Home.module.css'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Inventory Printing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <PrintButton/>
      </main>

    </div>
  )
}
